version: '3.8'

services:

  awkcalc:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=awkcalc.py
      - FLASK_ENV=production
